# Generated by Django 5.2.9 on 2025-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='helper_data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key_bytes',
            field=models.BinaryField(),
        ),
    ]
