"""
Django settings for securefiles project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from urllib.parse import parse_qs, unquote, urlparse
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ENVIRONMENT = os.getenv('DJANGO_ENV', 'production').lower()
IS_DEVELOPMENT = ENVIRONMENT in {'dev', 'development', 'local'}


def env_to_bool(value: str | None, *, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 't', 'yes', 'y', 'on'}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if IS_DEVELOPMENT:
        SECRET_KEY = 'django-insecure-local-dev-key'
    else:
        raise ValueError('SECRET_KEY environment variable must be set in production.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_to_bool(os.getenv('DEBUG'), default=IS_DEVELOPMENT)

if DEBUG:
    ALLOWED_HOSTS = [
        host.strip()
        for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
        if host.strip()
    ]
else:
    ALLOWED_HOSTS = [
        host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'securefiles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'securefiles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _database_from_url(database_url: str) -> dict[str, str | int]:
    parsed = urlparse(database_url)
    if parsed.scheme not in {'postgres', 'postgresql'}:
        raise ValueError('DATABASE_URL must use a postgres:// or postgresql:// scheme.')

    if not parsed.path or parsed.path == '/':
        raise ValueError('DATABASE_URL must include a database name in the path component.')

    options = {
        key: values[0]
        for key, values in parse_qs(parsed.query).items()
        if values
    }

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or 'localhost',
        'PORT': parsed.port or 5432,
        'OPTIONS': options,
    }


def _database_from_env_vars() -> dict[str, str | int] | None:
    required_vars = ('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT')
    if not any(os.getenv(var) for var in required_vars):
        return None

    missing_vars = [var for var in required_vars if not os.getenv(var)]
    if missing_vars:
        raise ValueError(
            'Missing required database environment variables: ' + ', '.join(missing_vars)
        )

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', ''),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': int(os.getenv('DB_PORT', '5432')),
    }


def _database_settings() -> dict[str, dict[str, str | int | Path | dict[str, str]]]:
    """
    Production database configuration:
    - Preferred: DATABASE_URL=postgres://USER:PASSWORD@HOST:PORT/NAME
    - Equivalent explicit vars: DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT

    Local fallback:
    - SQLite is used only when no Postgres settings are provided and DJANGO_ENV is local/dev.

    Pre-deploy migration check (against Postgres):
    - python manage.py migrate --plan
    - python manage.py migrate
    """

    database_url = os.getenv('DATABASE_URL')
    if database_url:
        return {'default': _database_from_url(database_url)}

    database_from_env = _database_from_env_vars()
    if database_from_env:
        return {'default': database_from_env}

    if IS_DEVELOPMENT:
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

    raise ValueError(
        'Production requires PostgreSQL settings. Set DATABASE_URL or '
        'DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT.'
    )

DATABASES = _database_settings()


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'mainapp.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'mainapp' / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set session to expire in 10 minutes (600 seconds)
SESSION_COOKIE_AGE = 600 
# Resets the 10-minute timer every time the user clicks something
SESSION_SAVE_EVERY_REQUEST = True

CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = env_to_bool(os.getenv('SECURE_SSL_REDIRECT'), default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
